name: PR Tests

on: pull_request

permissions:
  contents: read

jobs:
  tests:
    name: Run Tests
    runs-on: macOS-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
    - name: Build and run tests
      run: ./Scripts/build.sh tests
#      env:
#        DEVELOPER_DIR: '/Applications/Xcode_12.2.app/Contents/Developer'
